version: '2.1'

services:
  ptoj-db:
    image: mongo:latest
    container_name: ptoj-db
    restart: always
    volumes:
      - $PWD/migrations/db:/data/db
      - $PWD/migrations/backup:/data/backup

  ptoj-redis:
    image: redis:latest
    container_name: ptoj-redis
    restart: always

  ptoj-web-app:
    image: ptoj-web-app
    container_name: ptoj-web-app
    build: .
    environment:
      - NODE_ENV=production
      - dbURL=mongodb://ptoj-db:27017/oj
      - redisURL=redis://ptoj-redis:6379
    ports:
      - '0.0.0.0:80:3000'
    volumes:
      - $PWD/data:/app/data
      - $PWD/logs:/app/logs
      - /path/to/Judger:/services/Judger
      # warning: volumn is not available on building period
    depends_on:
      - ptoj-redis
      - ptoj-db
    restart: always
    cap_add:
      - SYS_PTRACE
