version: '2.1'

services:
  ptoj-db:
    image: mongo:latest
    container_name: ptoj-db
    restart: always
    volumes:
      - $PWD/migrations/db:/data/db
      - $PWD/migrations/backup:/data/backup
    ports:
      - '0.0.0.0:27017:27017'

  ptoj-redis:
    image: redis:latest
    container_name: ptoj-redis
    restart: always
    ports:
      - '0.0.0.0:6379:6379'
